---
- name: install lookaside prereqs
  package:
    name: 
      - python3
    state: installed

- name: Configuring httpd
  import_role:
    name: httpd
  vars:
    httpd_tls: True
  tags:
    - tls

- import_role:
    name: httpd
    tasks_from: pki-tls
  vars:
    pki_hostname: "{{ distgit_lookaside_httpd_hostname }}"
  notify:
    - restart_httpd
  tags:
    - tls

- name: make the lookaside cache directory
  file:
    path: "{{ lookaside_rootpath }}/lookaside"
    state: directory
    owner: apache
    group: apache
    mode: 0775
    setype: httpd_sys_rw_content_t

- name: Ensuring apache group can push to lookaside
  acl:
    entity: apache
    etype: group
    default: yes
    path: "{{ lookaside_rootpath }}/lookaside"
    permissions: rwx
    recursive: yes
    state: present

- name: install the upload.cgi script
  copy:
    src: "upload.cgi"
    dest: "/var/www/cgi-bin/upload.cgi"
    mode: 0755
    setype: "httpd_sys_script_exec_t"


- name: install the httpd config
  template:
    src: "etc/httpd/conf.d/lookaside.conf.j2"
    dest: "/etc/httpd/conf.d/lookaside.conf"
  notify:
    - reload httpd
